### ISSUE TITLE
Response is not JSON

### ISSUE THREAD

**Issue by dapperdandev** [scoutforpets/bookshelf-jsonapi-params#17]
Stack:
- hapi
- bookshelf
- MySQL

**controllers/driver.js**

```
'use strict';
var server = require( '../server' );
var bookshelf = require( '../bookshelf' );

var Driver = bookshelf.Model.extend( {
    tableName: 'Drivers'
} );

exports.index = server.route(
    {
        method: 'GET',
        path: '/drivers',
        config: {
            handler: function( request, reply ){
                Driver
                    .forge()
                    .fetchJsonApi()
                    .then((drivers) => {
                        reply(drivers);
                    });
            }
        }
    }
);
```

My response/reply is:

```
[
  {
    "id": "1",
    "first_name": "Name",
    "last_name": "Name",
    "license_number": "123456",
    "createdAt": "2016-07-05T16:00:00.000Z",
    "updatedAt": "2016-07-05T16:00:00.000Z"
  },
  {
    "id": "2",
    "first_name": "Name",
    "last_name": "Name",
    "license_number": "123456",
    "createdAt": "2016-07-05T16:00:00.000Z",
    "updatedAt": "2016-07-05T16:00:00.000Z"
  }
]
```

Expecting the data object/array.

I fully accept that I'm probably doing something wrong, but the only thing I feel like I'm doing differently is a reply() instead of return. Any thoughts?

**Comment by jamesdixon** [comment]
@djbreen7 are you configuring the plugin properly? https://github.com/scoutforpets/bookshelf-jsonapi-params#usage

**Comment by dapperdandev** [comment]
I believe so:

**bokshelf.js**

```
const dbConfig = require( './config/config' );

const knex = require('knex')({
    client: 'mysql',
    connection: dbConfig
});

const bookshelf = require('bookshelf')(knex);
const jsonApiParams = require('bookshelf-jsonapi-params');

bookshelf.plugin(jsonApiParams);
bookshelf.plugin('registry');

module.exports = bookshelf;
```

I'll push it up and share the repo

**Comment by dapperdandev** [comment]
https://github.com/djbreen7/ejs-taxi-hapi

Also, I'm using Node 4.4.7

**Comment by jamesdixon** [comment]
Just to be clear, you're expecting to a JSON API response, correct?

**Comment by dapperdandev** [comment]
Yes

**Comment by jamesdixon** [comment]
The issue is that this repo doesn't actually convert the response to JSON API. You need my other library: https://github.com/scoutforpets/jsonapi-mapper

**Comment by dapperdandev** [comment]
Cool. Thanks! Got a JSONAPI Response. I did the code slightly differently than the docs suggest. 
I used 

`const Mapper = require('jsonapi-mapper');` instead of `import Mapper = require('jsonapi-mapper');`

Typo?

[Commit: Get A JSONAPI Response](https://github.com/djbreen7/ejs-taxi-hapi/commit/ef401e563f30addc37e7216828916afcb9768cfd)

**Comment by dapperdandev** [comment]
Thanks a million for building these. Way to be leading the way. I really appreciate it

**Comment by jamesdixon** [comment]
Yep, that's a typo. Thanks!

**Comment by jamesdixon** [comment]
Of course! Feel free to contribute if you can. I can certainly use all the help I can get 👍

**Comment by dapperdandev** [comment]
I'll ping ya. I've only been a "professional" dev for 5 months. I'll write up a blog post on how I got things working. Not sure how much I can help in the source code, but I'll try.

**Comment by dapperdandev** [comment]
Jk. Github doesn't put emails out. I'm in the ember slack `dapperdan` if you're on there.
