### ISSUE TITLE
LIKE results in ER_PARSE_ERR in MySQL (incorrect use of quotes)

### ISSUE THREAD

**Issue by ErisDS** [scoutforpets/bookshelf-jsonapi-params#26]
I've been playing a little bit with the filtering feature which is in beta, using this module + https://github.com/kideh88/node-jsonapi-query-parser

For the most part, it seems to work pretty well, which is awesome 👍 

However, I'm having a problem using `like`.

E.g. A plain `eq` filter works just fine

`/users?filter[email]=me@myaddress.com`

However if I change it to 

`/users?filter[like][email]=@myaddress.com`

I get an error:

ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '."email") like LOWER('%@myaddress.com%')) limit 10' at line 1

The query that is being output is:

select count(distinct `users`.`id`) from `users` where (LOWER("users"."email") like LOWER('%@myaddress.com%'));

The problem is that whilst double quotes are correct syntax for postgres and sqlite3, this is not valid MySQL syntax. MySQL uses backticks.

There are some issues in knex around this: 
- https://github.com/tgriesser/knex/issues/872
- https://github.com/tgriesser/knex/issues/723
- https://github.com/tgriesser/knex/issues/1761

The solution seems to be to use a private API, taken from https://github.com/tgriesser/knex/issues/723#issuecomment-77772277

```
var formatter = new query.client.Formatter(); // Also this works too: new.knex.client.Formatter()
var columnName = formatter.columnize('member.name');
```

**Comment by alechirsch** [comment]
@ErisDS Thanks for pointing out that problem. When I implemented those features I was only considering postgres. Would you mind testing your idea and submitting a pull request?

I do not foresee having time to look into solving this problem.

Thanks!

**Comment by alechirsch** [comment]
@erisds did you ever get a chance to implement a fix?

**Comment by alechirsch** [comment]
@ErisDS Sorry I took over a year to finally get to this and figure it out, I believe I have solved the problem with my most recent PR
