### ISSUE TITLE
Usage with node-jsonapi-query-parser

### ISSUE THREAD

**Issue by astrotars** [scoutforpets/bookshelf-jsonapi-params#27]
You recommend using the node-jsonapi-query-parser module and that the produced object can be passed directly into the plugin without modification; however, when attempting to do so, nothing whatsoever happens... no filtering, nada. Any ideas? Your help is greatly appreciated!

**Comment by Moinax** [comment]
Hi @nparsons08 

I tried to use it too and I finally realised that we only need to pass the "queryData" property to the "fetchJsonApi" method and not the complete object.

I still trying to figure how to pass the "identifier" when I'm looking for a single resource, and I don't see how "relationships" and "relationshipType" could work with it.

**Comment by Moinax** [comment]
It seems that we can get a single resource by using the method "where" before calling the "fetchJsonApi" method (saw this in the tests).

So `model.forge({ id: 1 }).fetchJsonApi()` is not working
But `model.where({ id: 1}).fetchJsonApi()` is working

So what I do is checking if we have an "identifier" in the object provided by "node-jsonapi-query-parser" and use it in the "where" method.

    const attributes = {};
    if (req.data.identifier !== null) {
        attributes.id = req.data.identifier;
    }
    model.where(attributes).fetchJsonApi(req.data.queryData, req.data.identifier === null).then(...);

**Comment by jamesdixon** [comment]
@nparsons08 can you share your code?

**Comment by alechirsch** [comment]
I am closing this for now, @nparsons08 I will reopen if you still have problems?

**Comment by a-wf** [comment]
Hi, 

I have an issue, related with moinax talk about. 
How to handle the relationships like : https://jsonapi.org/format/#fetching-relationships

For instance, when I send a request to `/authors/{id}/relationships/books`, I get with the jsonapi-query-parser: 
```
{
  "resourceType": "authors",
  "identifier": {id},
  "relationships": true,
  "relationshipType": "books",
  "queryData": {
    "include": [],
    "fields": {},
    "sort": [],
    "page": {
      "offset": 0,
      "limit": 10
    },
    "filter": {
      "like": {},
      "not": {},
      "lt": {},
      "lte": {},
      "gt": {},
      "gte": {}
    }
  }
}
```
relationships is true, relationshipType is books,   I should get as result of bookshelf a array of books's id witthout attributes.

have you an idea about how to do that? 


Thank you!

**Comment by alechirsch** [comment]
@akdj Fetching relationships via "relationships" and "relationshipTypes" is currently not supported in this package. If you would like to take that on and try implementing it, I will certainly take a look.

**Comment by a-wf** [comment]
@alechirsch 
I read this parser's code, and finally understood that it is not the role of a fetch to do what I what. 

So I find another way this morning, I did this by using knex queryBuilder.select('id').innerJoin(...).where(...) then with jsonapi-mapper parsing the queried data with option attributes omit 'id'
