### ISSUE TITLE
Requires trailing slash on endpoint with node-jsonapi-query-parser

### ISSUE THREAD

**Issue by astrotars** [scoutforpets/bookshelf-jsonapi-params#28]
I was banging my head against the wall and then I had the bright idea to add a slash to the end of my URL. This fixed the issue with filtering not working with node-jsonapi-query-parser. Any thoughts on a permanent fix?

**Comment by alechirsch** [comment]
What did your URL look like before and after?

**Comment by astrotars** [comment]
**Before:**
`http://localhost:3000/users?filter[email]=gisipa@wi.na`

**After:**
`http://localhost:3000/users/?filter[email]=gisipa@wi.na`

**Comment by alechirsch** [comment]
It is strange that the extra slash affected the result. This seems like an issue with your server rather than the package. I am able to use it without a slash at the ends of the URLs.

**Comment by astrotars** [comment]
Yeah, very odd. I'm using Restify. So nothing crazy.

**Comment by alechirsch** [comment]
Can you post the code for the users route?

**Comment by astrotars** [comment]
Sure thing.

```
const Bookshelf               = require('../database'),
      jsonApiParams           = require('bookshelf-jsonapi-params'),
      jsonApiQueryParserClass = require('jsonapi-query-parser'),
      jsonApiQueryParser      = new jsonApiQueryParserClass()

Bookshelf.plugin(jsonApiParams)

const UsersModel = require('../models/user')

server.get('/users', (req, res, next) => {

    const query = jsonApiQueryParser.parseRequest(req.url)

    UsersModel
        .fetchJsonApi(query, true)
        .then(users => {
            res.send(users.toJSON())
        })
        .catch(err => {
            log.error(err)
            res.send(500)
        })

    return next()

})
```

**Comment by alechirsch** [comment]
You need to pass query.queryData to the fetchJsonApi function

```javascript
 UsersModel
        .fetchJsonApi(query.queryData, true)
        .then(users => {
            res.send(users.toJSON())
        })
        .catch(err => {
            log.error(err)
            res.send(500)
        })

    return next()
```

**Comment by astrotars** [comment]
It appears that when passing `query.queryData`, it kills the server with a rather verbose MySQL error message:

```
  ...
  "code": "ER_PARSE_ERROR",
  "errno": 1064,
  "sqlState": "42000",
  "index": 0,
  "level": "error",
  "timestamp": "Wed Dec 07 2016 22:26:04 GMT-0700 (MST)"
```

**Comment by alechirsch** [comment]
The changes that I made to this package seem to be having a negative affect on MySQL. Did that error give you the query that failed?

**Comment by astrotars** [comment]
`select `users`.* from `users` where `like` in ({}) and `not` in ({}) and `lt` in ({}) and `lte` in ({}) and `gt` in ({}) and `gte` in ({}) and `email` in ('tu@hijagnek.mw/') limit 1`

**Comment by alechirsch** [comment]
That is crazy, I'm not sure why it would be doing this only for MySQL, when I implemented the extra filtering features I was using postgresand never tested against MySQL. 

It is not supposed to be adding in those conditionals. 
Would you possibly have time to step through and figure out why it is adding those extra conditionals? I'm pretty busy at the moment with other projects.

**Comment by astrotars** [comment]
I'm also pretty limited on time and expertise with the project. Happy to help out however I can, though.

**Comment by alechirsch** [comment]
At some point I will have to take the time to install MySQL and figure out what's going on.

The current tests use SQLite, it may be a good idea to add tests for both MySQL and Postgres.

**Comment by alechirsch** [comment]
The version before the beta should work better with MySQL if you don't need the advanced filtering features.

**Comment by astrotars** [comment]
Thanks. I'll have to backdate my build a bit until we can come up with a solution. Thanks for the help!
