### ISSUE TITLE
Filter query always returns first result

### ISSUE THREAD

**Issue by astrotars** [scoutforpets/bookshelf-jsonapi-params#29]
A little stuck here. Getting ready to go live with my API using MySQL and I noticed that the filter query always returns the first result in the collection. Any thoughts?

**Comment by astrotars** [comment]
It was a late night, so I didn't think about dropping in an example. Here's my use-case:

I have a collection called kwh-rates that returns an array of objects containing kwh-rate objects:

```json
[
  {
    "id": "006f858c-3275-4351-9f4f-d09cca67879b",
    "state": "AR",
    "kwh_rate": 0.079,
    "created_at": "2017-01-05T04:29:56.000Z",
    "updated_at": "2017-01-05T04:29:56.000Z"
  },
  {
    "id": "007663b2-5fa6-4152-a20f-e1e508942006",
    "state": "IA",
    "kwh_rate": 0.0815,
    "created_at": "2017-01-05T04:33:17.000Z",
    "updated_at": "2017-01-05T04:33:17.000Z"
  }
]
```
From the browser, I need to filter down to a specific object (let's say IA), so I hit the API with the following:

```curl
http://localhost:3000/kwh-rates?filter[state]=IA
```

My response always comes back with the first result in the collection, for example:

```json
{
  "id": "006f858c-3275-4351-9f4f-d09cca67879b",
  "state": "AR",
  "kwh_rate": 0.079,
  "created_at": "2017-01-05T04:29:56.000Z",
  "updated_at": "2017-01-05T04:29:56.000Z"
}
```

It's definitely doing _something_, but it's not doing what I need it to do. Any thoughts here? I'm at a loss. It's such a great project with so much potential, just needs a few kinks ironed out. Also, for what it is worth, I'm using MySQL as my backend and my code looks like this:

```javascript
server.get('/kwh-rates', (req, res, next) => {

    let query = jsonApiQueryParser.parseRequest(req.url)

    KwhRatesModel
        .fetchJsonApi(query, true)
        .then(rates => {
            res.send(rates.toJSON())
        })
        .catch(err => {
            log.error(err)
            res.send(500)
        })

    return next()

})
```

**Comment by jamesdixon** [comment]
@nparsons08 I'm not sure offhand. Unfortunately, this isn't something I'm going to have time to look at. If you haven't already, I'd recommend tracing through to the plugin and see if you can't determine the issue at that level. 

In general, I admit that I haven't tested against MySQL. Ideally, we'd have tests for Postgres, MySQL and SQLite, but on the other hand, I believe that's already been done via the Bookshelf project. That said, I'm actually curious if this is a Bookshelf issue and not something to do with this project. You may want to take a peek in the issues section of the Bookshelf repo to see if answers may lie there.

If you do find something, please feel free to submit a PR. It would be appreciated! 

Cheers.

**Comment by alechirsch** [comment]
It looks like you are missing an important part in the code, try this: 

```
server.get('/kwh-rates', (req, res, next) => {

    let query = jsonApiQueryParser.parseRequest(req.url)

    KwhRatesModel
        .fetchJsonApi(query.queryData, true)
        .then(rates => {
            res.send(rates.toJSON())
        })
        .catch(err => {
            log.error(err)
            res.send(500)
        })

    return next()

})
```

Specifically this line: fetchJsonApi(query.queryData, true)

**Comment by astrotars** [comment]
@alechirsch Thanks for the heads up. It makes sense that I need that part. However, after adding it, I get a MySQL error stating that I have invalid SQL.

```
"message": "select `rates`.* from `rates` where `like` in ({}) and `not` in ({}) and `lt` in ({}) and `lte` in ({}) and `gt` in ({}) and `gte` in ({}) and `state` in ('CO') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') and `not` in () and `lt` in () and `lte` in () and `gt` in () and `gte` in () ' at line 1"
```

**Comment by astrotars** [comment]
It looks like 


```
`like` in ({}) and `not` in ({}) and `lt` in ({}) and `lte` in ({}) and `gt` in ({}) and `gte` in ({})
```

shouldn't be there if the object is empty.

**Comment by alechirsch** [comment]
It should not be there, it's a compatibility issue with MySQL. The sql
syntax is different between Postgres and MySQL.

**Comment by astrotars** [comment]
Definitely. Hopefully, that can be fixed in a future build. The `1.0.0-beta.1` release is working for me now. Had to manually drop that into `package.json` for it to be picked up. Thanks for the help!
