### ISSUE TITLE
implement "OR" filtering

### ISSUE THREAD

**Issue by jamesdixon** [scoutforpets/bookshelf-jsonapi-params#30]
@alechirsch I know we had briefly discussed a possible API to handle the case when you want to filter on _x_ OR _y_ rather than _x_ AND _y_.

Want to restart that discussion here and figure out an API?

**Comment by alechirsch** [comment]
Sure, I'd be happy to discuss it

**Comment by ErisDS** [comment]
Throwing in an idea here:

Ghost has a filter query language that works with JSON API's `?filter=` query param and supports  OR queries, it's called [GQL](https://github.com/TryGhost/GQL). The syntax is based on the filtering available in gmail, github and slack.

An example would be `?filter=foo:bar,bar:foo` - a comma denotes an OR. `?filter=foo:bar+bar:foo` - a plus denotes an AND. It does require URL encoding, however it's super flexible.

It's a bit unloved and needs a rewrite to squash some serious bugs in the first iteration, however as it's a simpler, shorter, slightly more powerful syntax I'd love to see more people make use of it. 

Support could be added in this lib and in https://github.com/kideh88/node-jsonapi-query-parser.

**Comment by alechirsch** [comment]
#63
