### ISSUE TITLE
Sort descending only ever works 1 time

### ISSUE THREAD

**Issue by ErisDS** [scoutforpets/bookshelf-jsonapi-params#35]
We've been experiencing issues with sort for a while, and haven't been able to figure out what was wrong. 

Yesterday, we ran some tests, and determined the behaviour is as follows:

If you use sort descending, e.g. `sort: ['-id']`, it works the first time you run the query, and therefore passes tests / appears to work. However all subsequent requests go back to sorting by ascended.

I believe the culprit is the line of code [`value = value.substr(1);`](https://github.com/scoutforpets/bookshelf-jsonapi-params/blob/master/src/index.js#L122)

In context:

```
// Loop through each sort value
_forEach(sortValues, (value) => {
    // If the sort value is descending, remove the dash
    if (value.indexOf('-') === 0){
        value = value.substr(1);
    }
    // Add relations to the relationHash
    internals.buildDependenciesHelper(value, relationHash);
});
```

If the sort value has a `-` at the start, it is overwritten without it. 

I think this is a pass-by-reference error, where the option is getting overwritten so that it no longer has the `-` on subsequent passes.

Not 100% sure if this is the culprit, but the behaviour indicates that something like this is happening.

**Comment by jamesdixon** [comment]
Thanks for reporting, @ErisDS!

Is this something you could write a failing test for and possibly a quick PR to fix?

Thx!
