### ISSUE TITLE
Support 'like' filter on postgresql jsonb columns

### ISSUE THREAD

**Issue by flmg** [scoutforpets/bookshelf-jsonapi-params#37]
Hey, great plugin!

I'm trying to use the `like` filter but it doesn't work on postgresql `jsonb` columns

`select "mytable".* from "mytable" where (LOWER("mytable"."jsoncolumn") like LOWER($1)) - function lower(jsonb) does not exist`

The request is generated by:

    qbWhere.where(
        Bookshelf.knex.raw(`LOWER(${formatedKey}) like LOWER(?), [`%${typeValue}%`])
    );

In postgresql, adding a `::text` does the job:
    
    select "mytable".*" from "mytable" where LOWER(("mytable"."jsoncolumn")::text) like LOWER('%test%');

Is there a way this could become a feature?

**Comment by alechirsch** [comment]
I personally think that is a good idea and do not see any problems with converting to text, I can look into doing this for postgres.

**Comment by alechirsch** [comment]
@flmg Something that I having been meaning to get to is fixing the compatibility issues between the newer filters features and MySQL. I would want to consider compatibility for this feature as well, I am not sure that MySQL supports that casting syntax.

**Comment by alexcouret** [comment]
@alechirsch Hi, I have just checked with MySQL, and it doesn't need any casting, as would PostgreSQL, so adding the `::text` cast on Postgres' side seems to be enough.

I tested on http://rextester.com/l/mysql_online_compiler with these queries:
`DROP TABLE IF EXISTS test;`
`CREATE TABLE test (enumtest ENUM('a', 'b', 'c'), jsontest JSON);`
`INSERT INTO test (enumtest, jsontest) VALUES ('b', '{"a": 1, "b": 2}');`
`SELECT * FROM test WHERE LOWER(jsontest) LIKE '%d%' OR lower(enumtest)='b';`

**Comment by alechirsch** [comment]
We would need to do something specific for each SQL syntax, meaning we need to add conditional code to do something different depending on the database being used.

After I implement this, I would love to get some help on getting test cases for every database supported by knex. The tests currently support only SQLite3.


Postgres, MSSQL, MySQL, MariaDB, SQLite3, and Oracle

**Comment by alechirsch** [comment]
@flmg @OzoTek Once my PR is published it should be working, feel free to review it.

**Comment by jamesdixon** [comment]
@alechirsch ill wait to publish to npm until you have this other PR merged

**Comment by alechirsch** [comment]
@jamesdixon Should be all set

**Comment by alexcouret** [comment]
@jamesdixon Thanks! Do you have an ETA as to when this will be published on npm?

**Comment by jamesdixon** [comment]
Just published v1.0.0 to NPM! Thanks to everyone for their hard work!
