### ISSUE TITLE
Implement json filtering

### ISSUE THREAD

**Issue by prieston** [scoutforpets/bookshelf-jsonapi-params#45]
As I see this plugin doens't support filitering columns with datatype json. Latest versions of postgres support json data type columns so I think it would be nice if this plugin also supported filtering for columns with data type json.

A sample of filtering would be 
`filter[column_json][property_1]=example`
or
`filter[like][column_json][property_1]=exam`

**Comment by jamesdixon** [comment]
Great idea! You’re more than welcome to submit a PR (with tests) for this functionality.

**Comment by alechirsch** [comment]
I will be looking into implementing this over the next few days. Ideas are welcome

**Comment by alechirsch** [comment]
My current plan is to keep the current API as is. An additional character will be used to specify where a json column is, this will be a colon `:`

To filter on a json column, you would do something like this:
`filter[like][metaData:prop1]=value`
If you are going through a relationship it would look like this:
`filter[like][rel.metaData:prop1]=value`
Filter multiple nested objects in the json field
`filter[like][rel.metaData:obj1.prop1]=value`

You can also specify the type of a property if filtering by `gt`, `lt`, `gte`, or `lte`
`filter[gt][rel.metaData:obj1.prop2:number]=60`
`filter[gt][rel.metaData:obj1.prop2:date]=01-01-2019`
`filter[gt][rel.metaData:obj1.prop2:timestamp]=01-01-2019:00:00:00`
Leaving the type out will default to a string

**Comment by alechirsch** [comment]
@jamesdixon We will need another way to test, since SQLite does not support json filtering, plus I am planning to implement only for Postgres at the moment.

**Comment by alechirsch** [comment]
@prieston published as `1.2.0`
