### ISSUE TITLE
query in one transaction failed

### ISSUE THREAD

**Issue by a-wf** [scoutforpets/bookshelf-jsonapi-params#53]
Hello, 

I am trying to use RLS system on my app. 
for that some of my queries should be in a same transaction. 

with fetch, fetchAll, I done it without issue
so after I see the code of the fetchJsonApi, I supposed that there is no issue with standard fetch option, like : {transacting: t}, it is supported. 

However, it seems that work not well,  I get : 
```unrecognized configuration parameter app.userid```
when I try to make a find query with SET app.userid TO ${userId}

**Comment by a-wf** [comment]
I found the issue, I think it is about the fetchPage

**Comment by alechirsch** [comment]
@akdj I am not sure how to help you with this, can you describe the problem in more detail?

**Comment by a-wf** [comment]
@alechirsch  Hi, I think my issue is not about the bookshelf-jsonapi-params

I am working on RLS (views, policies, triggers) system of postgreSQL. 

In my app, I am using bookshelf with pagination plugin

Each time I query, I put two queries in one transaction: 

```
knex.transaction(async (t) => {
   await this.bookshelf.knex.raw("SET myvirtualapp.userid TO '" + userId + "';").transacting(t);
   await this.db.models['modelExemple']
      .fetchPage({
        pageSize: pSize,
        page: p,
        transacting: t
      });
});
```
I get : 
```
error: unrecognized configuration parameter "myvirtualapp.userid"
````
with fetch and fetchAll works well. 


It maybe a issue of bookshelf or knex side. thanks for your reply
