### ISSUE TITLE
Filtering on related models

### ISSUE THREAD

**Issue by sebpowell** [scoutforpets/bookshelf-jsonapi-params#57]
I'm running into a problem when trying to filter relations. In Bookshelf, I would normally run the following query which should hopefully help to illustrate what I'm trying to do:

```javascript
await new Speaker().fetchAll({withRelated: [
	{
		"events": function(qb) {
			qb.where("format", "=", 1);
		}
	}
]});
```

Selecting fields for a relation seems to work in the following way:

/speakers?include=events&fields[events]=name

So I tried a similar approach for the above:

/speakers?include=events&filters[events][format]=1

But this doesn't work. I've also tried a few other things, but no luck so far. So I'm wondering if what I'm trying to do is even possible with this package?

It looks like this this has already been raised in the past, and as far as I can tell, a fix was applied (https://github.com/scoutforpets/bookshelf-jsonapi-params/issues/16) – but I'm not sure if this is fact working (and whether the above syntax is correct).

Any help would be greatly appreciated as I'm a bit stuck! Let me know if you need me to provide any additional info :)

**Comment by alechirsch** [comment]
What you are trying to do is not supported by this package. The relationship filtering that was implemented was to filter a model _by_ its relationships, rather than filtering the included relationships themselves. 

For example,  /speakers?include=events&filter[events.format]=1 would give you all speakers that have an event with a format of 1, with all their events included. 

What you want to achieve might need to be more specialized if you want it in a single call, where you add the code that you specified above. Another way to do it is to make additional api calls to fetch only the events that you want, filtered by the returned speakers.

**Comment by sebpowell** [comment]
@alechirsch – thanks for the quick response! Much appreciated :)

So just to make sure I've understood you correctly – the example you've provided would allow speakers to be filtered based on whether they have spoken at an event with the specified format. So effectively, we're filtering the collection of returned speakers, rather than the collection of events associated with each speaker. 

If so, then I think that solves my current problem as all I'm trying to do is display a list of speakers that have spoken at an event with a given format (e.g. all speakers that have spoken at a conference, rather than those that have only spoken at a meetup). 

But let's say I wanted to show all speakers, regardless of the kind of event they've spoken at, but for each speaker only show events of a given format. You mentioned adding the above code – could this be added via the 'additionalQuery' option? 

And lastly, out of interest – do you see any value in enabling the sort of query I've posted above within this package? Just curious whether I'm approaching this in the right way. 

Thanks again for your help, much appreciated.

**Comment by alechirsch** [comment]
Your first statement is correct, it will return what you laid out.

additionalQuery is applied to the speaker collection query. You can use the include parameter the same way you would use withRelated, so it's still possible to filter relationships. 

It might be possible to implement what you are looking for in this package. But in my experience so far I have not needed it, there is usually a workaround like making some additional queries with lazy loading.

**Comment by alechirsch** [comment]
@sebpowell If you are still interested in this feature we can discuss further, otherwise I might close this.
