### ISSUE TITLE
filtering on a 'hasMany' relationship with pagination results in less rows than expected

### ISSUE THREAD

**Issue by jvdgoltz** [scoutforpets/bookshelf-jsonapi-params#81]
Hi,

We have a model that has a `hasMany` relation. For example:
```javascript
const Tree = Bookshelf.Model.extend({
  ...,
});

const Forest = Bookshelf.Model.extend({
  trees: function() {
    return this.hasMany('Tree');
  },
  ...,
});
```

If we now make a query like this:
```javascript
Forest.fetchJsonApi({
  filter: {
    'trees.name': 'maple',
  },
  page: {
    page: 1,
    pageSize: 12,
  },
});
```
we expect to get the first 12 forests that have maple trees inside them. In reality we get less than 12, as it seems that either:
- first the rows are fetched and then the filter is applied _or_
- the `pageSize` parameter refers to the number of trees and not to the number of forests as the `join` operation results in more rows being returned than there are forests due to the `hasMany` relationship.

Could you point us to a solution? We are willing to also contribute a PR, but would be grateful for some help.

Thanks in advance and best regards!

**Comment by alechirsch** [comment]
Think about it from the SQL query perspective.

This generates the query
```
select forests.*
from forests
left outer join trees on forest_id=forests.id
where trees.name='maple'
limit 12
```
If you run this query on your database you should see the same exact results that the package returns.
There are a couple of things that you can do here:
- Add distinct keyword to the query
```
Forest.fetchJsonApi({
  filter: {
    'trees.name': 'maple',
  },
  page: {
    page: 1,
    pageSize: 12,
  },
}, true, null, qb => { qb.distinct() });
```
- Use an exists keyword instead of filter
```
Forest.fetchJsonApi({
  page: {
    page: 1,
    pageSize: 12,
  },
}, true, null, qb => {
 qb.whereExists(knex('trees').select('id').whereRaw('forest_id = forests.id'));
});
```

**Comment by jvdgoltz** [comment]
Hi Alec,
thanks for your quick and useful reply.
The first solution works, we haven't tested the second one.
For completeness, we also had to add a `qb.select(...)` to the query when we want to sort by a column name from a relation. Otherwise you will get a `for SELECT DISTINCT, ORDER BY expressions must appear in select list`.
