### ISSUE TITLE
Descending sort arguments are getting incorrectly transformed

### ISSUE THREAD

**Issue by kwelch2015** [scoutforpets/bookshelf-jsonapi-params#9]
We are seeing invalid results when passing in a descending sort argument.  Basically it ignores this part of the JSON API Spec: 'The sort order for each sort field MUST be ascending unless it is prefixed with a minus (U+002D HYPHEN-MINUS, “-“), in which case it MUST be descending.'  Sort arguments prefixed with a minus are not being properly processed.  

We think you could resolve it in the buildSort function.  You could to check for sort params passed with a minus (meaning descending sort), store the sort direction, remove the minus before formatting the arguments and call internals.model.orderBy() with the secondary optional argument supplying the sort direction you saved earlier.

**Comment by jamesdixon** [comment]
Thanks for reporting, @kwelch2015. You are correct -- definitely an issue. Not sure when I'll be able to get to this, but more than happy to accept a PR.

**Comment by kwelch2015** [comment]
All set - we submitted one.

**Comment by jamesdixon** [comment]
Thanks @kwelch2015 @jdevries. Merged and released as 0.4.0.
